// alpha keys
#define INPUT_KB_A 65
#define INPUT_KB_B 66
#define INPUT_KB_C 67
#define INPUT_KB_D 68
#define INPUT_KB_E 69
#define INPUT_KB_F 70
#define INPUT_KB_G 71
#define INPUT_KB_H 72
#define INPUT_KB_I 73
#define INPUT_KB_J 74
#define INPUT_KB_K 75
#define INPUT_KB_L 76
#define INPUT_KB_M 77
#define INPUT_KB_N 78
#define INPUT_KB_O 79
#define INPUT_KB_P 80
#define INPUT_KB_Q 81
#define INPUT_KB_R 82
#define INPUT_KB_S 83
#define INPUT_KB_T 84
#define INPUT_KB_U 85
#define INPUT_KB_V 86
#define INPUT_KB_W 87
#define INPUT_KB_X 88
#define INPUT_KB_Y 89
#define INPUT_KB_Z 90

// numeric keys
#define INPUT_KB_0 48
#define INPUT_KB_1 49
#define INPUT_KB_2 50
#define INPUT_KB_3 51
#define INPUT_KB_4 52
#define INPUT_KB_5 53
#define INPUT_KB_6 54
#define INPUT_KB_7 55
#define INPUT_KB_8 56
#define INPUT_KB_9 57

// extra keys
#define INPUT_KB_SPACE 32

// mouse buttons
#define INPUT_LMB 0
#define INPUT_RMB 1
#define INPUT_MMB 2
#define INPUT_MB4 3
#define INPUT_MB5 4
#define INPUT_M_BACK INPUT_MB4
#define INPUT_M_FORW INPUT_MB5

// controller axis
#define INPUT_CONTROLLER_AXIS_LH 0
#define INPUT_CONTROLLER_AXIS_LV 1
#define INPUT_CONTROLLER_AXIS_TRIGGER 2
#define INPUT_CONTROLLER_AXIS_RV 3
#define INPUT_CONTROLLER_AXIS_RH 4

// controller buttons
#define INPUT_CONTROLLER_A 0
#define INPUT_CONTROLLER_B 1
#define INPUT_CONTROLLER_X 2
#define INPUT_CONTROLLER_Y 3
#define INPUT_CONTROLLER_LB 4
#define INPUT_CONTROLLER_RB 5
#define INPUT_CONTROLLER_BACK 6
#define INPUT_CONTROLLER_START 7
#define INPUT_CONTROLLER_LSTICK 8
#define INPUT_CONTROLLER_RSTICK 9
